import {initializeApp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import {getDatabase,ref,get,onValue,update,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import {getAuth,GithubAuthProvider,GoogleAuthProvider,signInWithPopup,signInAnonymously,signOut,onAuthStateChanged,setPersistence,browserLocalPersistence} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {firebaseConfig} from "./firebase-config.js?v=40";
import {currentSeasonId,findDriver,normalizeName,rebuildStandings,slugify,sortedStandings,teamBranding} from "./competition-model.js?v=79";

const app=initializeApp(firebaseConfig),db=getDatabase(app),auth=getAuth(app),$=id=>document.getElementById(id);
const githubProvider=new GithubAuthProvider(),googleProvider=new GoogleAuthProvider();
const ADMIN_UIDS=new Set(["2DCyQB0Js1UpWGI0LkEQtnOhGPl1","UqAXXX1tq9d5I34QTF3USu3vaUb2"]);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
let competition={},user=null,binding=null,driverProfile=null,mode=null,bindingUnsubscribe=null;

setPersistence(auth,browserLocalPersistence).catch(()=>{});
function setConnection(text,kind=""){const el=$("champ-connection");el.className=`pill ${kind}`;el.querySelector("span:last-child").textContent=text}
function friendlyError(error){console.error(error);return error?.code==="PERMISSION_DENIED"||error?.code==="permission-denied"?"Permission denied. Confirm this device is approved and try again.":error?.message||"Unable to complete that request."}
async function ensureAnonymous(){if(auth.currentUser?.isAnonymous)return auth.currentUser;return (await signInAnonymously(auth)).user}
function savedProfile(){try{return JSON.parse(localStorage.getItem("mfma-driver-profile")||"null")}catch{return null}}
function saveProfile(profile){driverProfile=profile;localStorage.setItem("mfma-driver-profile",JSON.stringify(profile))}

async function driverSignIn(event){event.preventDefault();const match=findDriver(competition.drivers,$("champ-driver-name").value,$("champ-driver-number").value);if(!match){$("champ-driver-status").textContent="No approved driver matches that name and MRA number.";return}try{const signedIn=await ensureAnonymous(),[driverId,driver]=match,access=(await get(ref(db,`mfma/driverAccess/${signedIn.uid}`))).val(),boundTeamId=access?.teamId||competition.drivers?.[access?.driverId]?.teamId;if(access?.status!=="approved"||boundTeamId!==driver.teamId){await update(ref(db,`mfma/requests/access/${signedIn.uid}`),{uid:signedIn.uid,teamId:driver.teamId,teamName:driver.teamName,status:"pending",requestedAt:serverTimestamp()});$("champ-driver-status").textContent="Team-device access requested. MRA approval is required once per device.";return}saveProfile({driverId,driverName:driver.name,mraNumber:driver.mraNumber,teamId:driver.teamId,teamName:driver.teamName});mode="driver";renderAccess()}catch(error){$("champ-driver-status").textContent=friendlyError(error)}}

async function providerSignIn(provider,label){$("champ-admin-status").textContent=`Opening ${label} sign-in…`;try{await signInWithPopup(auth,provider)}catch(error){$("champ-admin-status").textContent=friendlyError(error)}}
function renderAccess(){const active=mode==="admin"||mode==="driver";$("champ-auth").classList.toggle("hidden",active);$("champ-portal").classList.toggle("hidden",!active);if(!active)return;const admin=mode==="admin",driver=competition.drivers?.[driverProfile?.driverId];$("champ-role").textContent=admin?"MRA Championship Administration":"MFMA Driver Championship";$("champ-welcome").textContent=admin?"Race Management":driver?.name||driverProfile?.driverName||"Driver";$("champ-subtitle").textContent=admin?"Manage events, entries, standings, and the official archive.":`${driver?.teamName||driverProfile?.teamName||"Independent"} • MRA ${driver?.mraNumber||driverProfile?.mraNumber||""}`;$("champ-race-control").classList.toggle("hidden",!admin);$("champ-event-create").classList.toggle("hidden",!admin);renderAll()}

function sourceStandings(season,type){const all=Object.values(competition.archives||{}).flatMap(value=>Object.entries(value||{}));const source=season==="career"?rebuildStandings(Object.fromEntries(all)):competition.standings?.[season];return sortedStandings(source?.[type])}
function rowTeamId(row,type){return type==="teams"?row.id:type==="drivers"?competition.drivers?.[row.id]?.teamId:competition.vehicles?.[row.id]?.teamId}
function renderStandings(){const season=$("champ-season").value||currentSeasonId(),type=$("champ-standing-type").value,rows=sourceStandings(season,type);$("champ-standings").innerHTML=rows.map((row,index)=>{const teamId=rowTeamId(row,type),brand=teamBranding(teamId);return `<article class="champ-standing-row" style="--team-accent:${escapeHtml(brand.accent)}"><b class="champ-position">${index+1}</b><div class="champ-entrant">${brand.emblem?`<img src="${escapeHtml(brand.emblem)}" alt="">`:`<span class="team-fallback">${escapeHtml((row.name||"?")[0])}</span>`}<span><strong>${escapeHtml(row.name)}</strong><small>${escapeHtml(competition.teams?.[teamId]?.name||"")}</small></span></div><div><strong>${row.wins||0}</strong><small>Wins</small></div><div><strong>${row.podiums||0}</strong><small>Podiums</small></div><div class="champ-points"><strong>${row.points||0}</strong><small>Points</small></div></article>`}).join("")||'<p class="empty-state">No points have been awarded yet. Results appear here when Race Control archives an event.</p>'}
function eventEntries(eventId){return Object.values(competition.eventRegistrations?.[eventId]||{})}
function renderEvents(){const events=Object.entries(competition.events||{}).sort((a,b)=>(a[1].date||"").localeCompare(b[1].date||""));$("champ-events").innerHTML=events.map(([id,event])=>{const entries=eventEntries(id),registered=driverProfile&&entries.some(item=>item.driverId===driverProfile.driverId);return `<article class="champ-event-card"><div><span class="event-status ${escapeHtml(event.registrationStatus||"closed")}">${escapeHtml(event.registrationStatus==="open"?"Registration Open":"Registration Closed")}</span><h3>${escapeHtml(event.name)}</h3><p>${escapeHtml(event.date||"Date TBA")} • ${escapeHtml(event.seasonId||"")}</p></div><div class="event-entry-summary"><strong>${entries.length}</strong><span>${entries.length===1?"Entry":"Entries"}</span></div>${mode==="driver"&&event.registrationStatus==="open"?`<button class="action ${registered?"secondary-btn":"primary-btn"}" data-event-register="${escapeHtml(id)}" type="button">${registered?"Update Entry":"Register"}</button>`:""}${mode==="admin"?`<button class="action secondary-btn" data-event-toggle="${escapeHtml(id)}" type="button">${event.registrationStatus==="open"?"Close Registration":"Open Registration"}</button>`:""}<div class="event-entry-list">${entries.map(entry=>`<span><b>${escapeHtml(entry.driverName)}</b><small>${escapeHtml(entry.vehicleName)} • ${escapeHtml(entry.teamName)}</small></span>`).join("")||"<p>No entries yet.</p>"}</div></article>`}).join("")||'<p class="empty-state">No championship events are open yet. MRA can create the first event here.</p>';document.querySelectorAll("[data-event-register]").forEach(button=>button.onclick=()=>openRegistration(button.dataset.eventRegister));document.querySelectorAll("[data-event-toggle]").forEach(button=>button.onclick=()=>toggleEvent(button.dataset.eventToggle))}
function renderTeams(){$("champ-teams").innerHTML=Object.entries(competition.teams||{}).filter(([,team])=>team.status==="approved").map(([id,team])=>{const brand=teamBranding(id),drivers=Object.values(competition.drivers||{}).filter(driver=>driver.status==="approved"&&driver.teamId===id);return `<article class="champ-team-card" style="--team-accent:${escapeHtml(brand.accent)}">${brand.logo?`<img class="team-wordmark" src="${escapeHtml(brand.logo)}" alt="${escapeHtml(team.name)}">`:`<div class="team-fallback large">${escapeHtml(team.name[0])}</div>`}<h3>${escapeHtml(team.name)}</h3><div>${drivers.map(driver=>`<span><b>${escapeHtml(driver.name)}</b><small>MRA ${escapeHtml(driver.mraNumber)}</small></span>`).join("")||"<p>No approved drivers.</p>"}</div></article>`}).join("")||'<p class="empty-state">No registered teams yet.</p>'}
function renderHistory(){const events=Object.values(competition.archives||{}).flatMap(season=>Object.values(season||{})).sort((a,b)=>(b.endedAt||0)-(a.endedAt||0));$("champ-history").innerHTML=events.map(event=>`<article class="archive-card"><div><strong>${escapeHtml(event.name)}</strong><span>${escapeHtml(event.date||"")} • ${escapeHtml(event.seasonId||"")}</span></div><ol>${(event.classification||[]).map(row=>`<li><span>${escapeHtml(row.driverName||row.vehicleName||"Unassigned")}</span><b>${row.points||0} pts</b></li>`).join("")}</ol></article>`).join("")||'<p class="empty-state">No completed races have been archived yet.</p>'}
function renderAll(){const seasons=new Set([currentSeasonId(),...Object.keys(competition.seasons||{}),...Object.keys(competition.archives||{})]),select=$("champ-season"),prior=select.value;select.innerHTML='<option value="career">Career</option>'+[...seasons].sort().reverse().map(id=>`<option>${escapeHtml(id)}</option>`).join("");select.value=prior==="career"||seasons.has(prior)?prior:currentSeasonId();renderStandings();renderEvents();renderTeams();renderHistory()}

function openRegistration(eventId){const event=competition.events?.[eventId],driver=competition.drivers?.[driverProfile?.driverId],prior=competition.eventRegistrations?.[eventId]?.[driverProfile?.driverId];if(!event||!driver)return;$("registration-event-id").value=eventId;$("registration-event-title").textContent=event.name;$("registration-team-name").value=driver.teamName;$("registration-vehicle-id").value=prior?.vehicleId||"ranger";$("registration-event-status").textContent="";$("event-registration-dialog").showModal()}
async function submitRegistration(event){event.preventDefault();const eventId=$("registration-event-id").value,eventRecord=competition.events?.[eventId],driver=competition.drivers?.[driverProfile?.driverId],vehicleId=$("registration-vehicle-id").value,vehicleNames={ranger:"Ranger",shelly:"Shelly",gator:"Gator"};if(!eventRecord||eventRecord.registrationStatus!=="open"||!driver||!vehicleNames[vehicleId])return;const registeredAt=Date.now();try{await update(ref(db,`mfma/competition/eventRegistrations/${eventId}/${driverProfile.driverId}`),{driverId:driverProfile.driverId,driverName:driver.name,mraNumber:driver.mraNumber,teamId:driver.teamId,teamName:driver.teamName,vehicleId,vehicleName:vehicleNames[vehicleId],status:"registered",registeredAt});$("registration-event-status").textContent="Registered. Your vehicle and team are now listed for Race Control.";setTimeout(()=>$("event-registration-dialog").close(),900)}catch(error){$("registration-event-status").textContent=friendlyError(error)}}
async function createEvent(event){event.preventDefault();const id=`${$("champ-event-date").value}-${slugify($("champ-event-name").value)}-${Date.now().toString(36)}`;try{await update(ref(db,`mfma/competition/events/${id}`),{name:normalizeName($("champ-event-name").value),date:$("champ-event-date").value,seasonId:String($("champ-event-season").value||currentSeasonId()).slice(0,4),registrationStatus:$("champ-event-registration").value,status:"scheduled",createdAt:serverTimestamp()});$("champ-event-admin-status").textContent="Championship event created.";event.target.reset();$("champ-event-date").value=new Date().toISOString().slice(0,10);$("champ-event-season").value=currentSeasonId()}catch(error){$("champ-event-admin-status").textContent=friendlyError(error)}}
async function toggleEvent(id){const event=competition.events?.[id];if(!event)return;await update(ref(db,`mfma/competition/events/${id}`),{registrationStatus:event.registrationStatus==="open"?"closed":"open"})}

$("champ-driver-form").onsubmit=driverSignIn;$("champ-github").onclick=()=>providerSignIn(githubProvider,"GitHub");$("champ-google").onclick=()=>providerSignIn(googleProvider,"Google");$("champ-sign-out").onclick=async()=>{mode=null;driverProfile=null;localStorage.removeItem("mfma-driver-profile");localStorage.setItem("mfma-driver-signed-out","1");await signOut(auth);renderAccess()};$("champ-season").onchange=renderStandings;$("champ-standing-type").onchange=renderStandings;$("champ-event-create").onsubmit=createEvent;$("event-registration-form").onsubmit=submitRegistration;$("registration-close").onclick=()=>$("event-registration-dialog").close();document.querySelectorAll("[data-champ-tab]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-champ-tab]").forEach(item=>item.classList.toggle("active",item===button));document.querySelectorAll(".champ-view").forEach(view=>view.classList.add("hidden"));$(`champ-view-${button.dataset.champTab}`).classList.remove("hidden")});

onValue(ref(db,"mfma/competition"),snapshot=>{competition=snapshot.val()||{};setConnection("Live","connected");if(driverProfile){const driver=competition.drivers?.[driverProfile.driverId];if(!driver){driverProfile=null;mode=null}else saveProfile({...driverProfile,driverName:driver.name,mraNumber:driver.mraNumber,teamId:driver.teamId,teamName:driver.teamName})}renderAccess()},()=>setConnection("Offline","offline"));
onAuthStateChanged(auth,current=>{user=current;if(bindingUnsubscribe){bindingUnsubscribe();bindingUnsubscribe=null}if(current&&!current.isAnonymous){if(ADMIN_UIDS.has(current.uid)){mode="admin";driverProfile=null}else{$("champ-admin-status").textContent="This account is not authorized for MRA administration.";mode=null}renderAccess();return}if(current?.isAnonymous){bindingUnsubscribe=onValue(ref(db,`mfma/driverAccess/${current.uid}`),snapshot=>{binding=snapshot.val();const profile=savedProfile(),driver=competition.drivers?.[profile?.driverId],teamId=binding?.teamId||competition.drivers?.[binding?.driverId]?.teamId;if(binding?.status==="approved"&&profile?.teamId===teamId&&driver?.teamId===teamId){driverProfile=profile;mode="driver"}renderAccess()})}});
$("champ-event-date").value=new Date().toISOString().slice(0,10);$("champ-event-season").value=currentSeasonId();const profile=savedProfile();if(profile){$("champ-driver-name").value=profile.driverName||"";$("champ-driver-number").value=profile.mraNumber||""}renderAccess();
