import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getDatabase, ref, onValue, get, update, push, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import { getAuth, onAuthStateChanged, signInAnonymously } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { firebaseConfig } from "./firebase-config.js?v=40";
import { signals } from "./signals.js?v=94";
import { getRenderMode } from "./display-state.js?v=87";
import { enableSounds, getSoundStatus, onSoundStatus, playStateTransition } from "./sounds.js?v=74";
import { cleanOccupantReport, cleanHazardReport } from "./report-model.js?v=52";
import { activeTrackSignals, hasGripSignal, trackOutlineMarkup } from "./track-signals.js?v=3";
import { LEGACY_VEHICLES, applyStandingsAdjustments, isScoringDriverEligible, normalizeMraNumber, normalizeName, currentSeasonId, rebuildStandings } from "./competition-model.js?v=89";
import {QUALIFYING_TRACKS,fastestQualifyingLap,qualifyingTime,rankedQualifyingLaps} from "./qualifying-model.js?v=85";
const app=initializeApp(firebaseConfig),db=getDatabase(app),auth=getAuth(app),stateRef=ref(db,"mfma/state");
const $=id=>document.getElementById(id);let state=null,wake=null;
const display=$("display"),status=$("display-status"),statusText=status.querySelector("span:last-child"),statusView=$("status-view"),liveView=$("live-view"),title=$("status-title"),detail=$("status-detail"),kicker=$("status-kicker"),sessionLine=$("display-session"),timer=$("display-timer"),label=$("label"),instruction=$("instruction"),theme=document.querySelector('meta[name="theme-color"]'),standbyLeaderboard=$("standby-leaderboard");
const soundButton=$("display-sound");
const vehicleSelect=$("driver-vehicle"),tools=$("driver-tools"),PROFILE_KEY="mfma-driver-profile";
function readDriverProfile(){try{const profile=JSON.parse(localStorage.getItem(PROFILE_KEY)||"null");return profile?.teamId&&profile?.driverId&&profile?.vehicleId?profile:null}catch{return null}}
let driverProfile=readDriverProfile(),selectedVehicle=driverProfile?.vehicleId||localStorage.getItem("mfma-driver-vehicle")||"ranger",competition={};
let driverUser=null,driverAuthPromise=null,crewEditing=false,lastReportKey="",resolvedTimer=null,accessUnsubscribe=null,currentBinding=null;
const safetyManagementFlags=new Set(["yellow","grip-deterioration","move-over","red","safety-car","return-to-start","infraction-warning","under-review","disqualification"]);
const acknowledgedInstructionTypes=new Set(["red","safety-car","return-to-start","proceed-to-start","restart"]);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]);
let visualSignal=null;
function applyDisplayClass(className,signal){
 if(signal!==visualSignal&&display.classList.contains("flash")&&className.includes(" flash")){
  display.classList.remove("flash");void display.offsetWidth;
 }
 const trackSignals=activeTrackSignals(state?.trackSignals),grip=trackSignals.find(item=>item.grip);display.className=`${className}${trackSignals.length?" has-track-signals":""}${grip?" grip-advisory":""}`;display.dataset.gripCondition=grip?.type||"surface";visualSignal=signal;
}
function fmt(ms){const t=Math.max(0,Math.ceil(ms/1000));return `${String(Math.floor(t/60)).padStart(2,"0")}:${String(t%60).padStart(2,"0")}`}
function fmtQualifying(ms){const value=Math.max(0,Math.floor(ms||0));return `${String(Math.floor(value/60000)).padStart(2,"0")}:${String(Math.floor(value%60000/1000)).padStart(2,"0")}.${String(value%1000).padStart(3,"0")}`}
function sprintTime(s=state?.sprint){if(!s||s.timerMode==="none")return 0;const delta=s.running?Math.max(0,Date.now()-(s.lastTickAt||Date.now())):0;return s.timerMode==="count-up"?Math.max(0,(s.elapsedMs||0)+delta):Math.max(0,(s.remainingMs||0)-delta)}
async function awake(){try{if("wakeLock"in navigator)wake=await navigator.wakeLock.request("screen")}catch(_){}}
function showStatus(t,d,k="MFMA COMPETITION NETWORK"){
 statusView.classList.remove("hidden");liveView.classList.add("hidden");
 $("qualifying-leaderboard").classList.add("hidden");
 title.textContent=t;detail.textContent=d;kicker.textContent=k;
 standbyLeaderboard.classList.add("hidden");standbyLeaderboard.innerHTML="";
 applyDisplayClass("display flag-clear","status");theme.content="#0d1117";
}
function showLive(){const sig=signals[state.activeFlag]||signals.clear,s=state.session,awaiting=s.phase==="awaiting-finding-start";statusView.classList.add("hidden");liveView.classList.remove("hidden");applyDisplayClass(`display ${sig.className}${sig.flash?" flash":""}`,`${state.systemState}:${state.activeFlag}:${s.phase}`);label.textContent=awaiting?"HIDING COMPLETE":sig.label;instruction.textContent=awaiting?"Awaiting MRA Steward.":sig.instruction;theme.content=sig.theme;sessionLine.textContent=awaiting?`SESSION ${s.number} • AWAITING FINDING START`:`SESSION ${s.number} • ${s.phase.toUpperCase()} • PURSUIT: ${s.teamNames[s.pursuitTeam]} • EVADING: ${s.teamNames[s.evadingTeam]}`;timer.textContent=fmt(s.remainingMs)}
function showStandbyFlag(){
 const flag=state.activeFlag||"clear",sig=signals[flag]||signals.clear;
 if(flag==="clear"){showStatus("STANDBY","Event active. No session is live.",state.event.name);return}
 const copy={yellow:["CAUTION","OPERATIONAL SIGNAL"],"move-over":["MOVE OVER","ALLOW FASTER VEHICLE TO PASS"],red:["STOP","AWAIT RACE CONTROL INSTRUCTIONS"],"safety-car":["SAFETY CAR","FOLLOW SAFETY CAR • NO OVERTAKING"],"infraction-warning":["INFRACTION WARNING","WHITE + FOLDED YELLOW"],disqualification:["DISQUALIFIED","RETURN TO STARTING ZONE"],checkered:["CHECKERED","OPERATIONAL SIGNAL"]}[flag]||[sig.label,sig.instruction];
 statusView.classList.add("hidden");liveView.classList.remove("hidden");applyDisplayClass(`display ${sig.className}${sig.flash?" flash":""}`,`standby:${flag}`);
 label.textContent=copy[0];instruction.textContent=copy[1];sessionLine.textContent=`${state.event.name} • STANDBY`;timer.textContent="--:--";theme.content=sig.theme;
}
function showSprint(){
 const flag=state.activeFlag||"clear",sig=signals[flag]||signals.clear,s=state.sprint||{};
 const labels={clear:"CLEAR",green:"GREEN",yellow:"YELLOW","grip-deterioration":"GRIP DETERIORATION","move-over":"MOVE OVER",red:"RED","safety-car":"SAFETY CAR","infraction-warning":"INFRACTION WARNING",disqualification:"DISQUALIFIED",checkered:"CHECKERED"};
 statusView.classList.add("hidden");liveView.classList.remove("hidden");applyDisplayClass(`display ${sig.className}${sig.flash?" flash":""}`,`sprint:${flag}`);
 label.textContent=labels[flag]||flag.toUpperCase();instruction.textContent=flag==="safety-car"?"FOLLOW SAFETY CAR • NO OVERTAKING":flag==="grip-deterioration"?"GRIP • GRIP • GRIP":"MFMA SPRINT • OPERATIONAL SIGNAL";sessionLine.textContent="MFMA SPRINT • FLAG OPERATIONS";timer.textContent=s.timerMode==="none"?"NO FORMAL SESSION":fmt(sprintTime(s));theme.content=sig.theme;
}
function showQualifying(){const qualifying=state.event?.qualifying||{},laps=rankedQualifyingLaps(qualifying.laps),leaders=laps.filter((lap,index)=>laps.findIndex(item=>item.driverId===lap.driverId)===index),fastest=leaders[0],board=$("qualifying-leaderboard"),warmup=!qualifying.warmupCompleted,halfway=state.activeFlag==="qualifying-halfway",completed=Object.values(qualifying.laps||{}).filter(lap=>lap?.driverId===qualifying.currentDriverId).length,limit=qualifying.lapLimit||5;statusView.classList.add("hidden");liveView.classList.remove("hidden");applyDisplayClass(`display flag-qualifying${halfway?" flag-qualifying-halfway flash":""}`,"qualifying");label.textContent=warmup?"WARM-UP LAP":halfway?"HALFWAY":qualifying.running?"QUALIFYING LAP":"QUALIFYING";instruction.textContent=warmup?"UNTIMED • SHELLY":halfway?"CROSSED GREEN + CHECKERED":qualifying.running?`${qualifying.currentDriverName||"DRIVER"} • LAP ${completed+1} OF ${limit}`:(fastest?`FASTEST • ${fastest.driverName} • ${fmtQualifying(fastest.timeMs)}`:"AWAITING FIRST LAP");sessionLine.textContent=`${(QUALIFYING_TRACKS[qualifying.trackLength]||"QUALIFYING").toUpperCase()} TRACK • SHELLY`;timer.textContent=warmup?"WARM-UP":fmtQualifying(qualifyingTime(qualifying));board.classList.toggle("hidden",warmup||!leaders.length);board.innerHTML=leaders.slice(0,5).map((lap,index)=>`<span class="${lap.driverId===driverProfile?.driverId?"current-driver":""}"><b>${index+1}</b><strong>${escapeHtml(lap.driverName)}</strong><time>${fmtQualifying(lap.timeMs)}</time></span>`).join("");theme.content=halfway?"#16261a":"#10141b"}
function showTestMode(){const flag=state.activeFlag||"clear",sig=signals[flag]||signals.clear;statusView.classList.add("hidden");liveView.classList.remove("hidden");applyDisplayClass(`display test-mode-display ${sig.className}${sig.flash?" flash":""}`,`test:${flag}`);label.textContent=flag==="clear"?"TEST MODE":sig.label;instruction.textContent="DISPLAY / SOUND VERIFICATION • NOT AN ACTIVE EVENT";sessionLine.textContent=`MRA SYSTEM TEST • ${flag.replaceAll("-"," ").toUpperCase()}`;timer.textContent="TEST";theme.content=sig.theme;tools.classList.add("hidden")}
function renderStartDots(){const endsAt=state.session?.countdownEndsAt||Date.now(),elapsed=Math.max(0,10000-(endsAt-Date.now())),lit=elapsed<9300?Math.min(5,Math.floor(elapsed/1500)+1):0;timer.innerHTML=Array.from({length:5},(_,index)=>`<span class="${index<lit?"lit":"out"}"><i></i><i></i></span>`).join("")}
function renderSafetyManagement(){const managed=safetyManagementFlags.has(state?.activeFlag)||activeTrackSignals(state?.trackSignals).length>0,message=safetyManagementFlags.has(state?.activeFlag)&&state.safetyMessage?.flag===state.activeFlag?String(state.safetyMessage.text||"").trim():"",panel=$("safety-management"),brand=$("display-brand-logo");panel.classList.toggle("hidden",!message);$("safety-message").textContent=message;panel.classList.toggle("has-message",Boolean(message));brand.src=managed?"assets/branding/mra-logo.png":"assets/branding/mfma-logo.png";brand.alt=managed?"MRA — MFMA Race Authority":"MFMA"}
function renderTrackAdvisory(){let panel=$("track-advisory");if(!panel){panel=document.createElement("aside");panel.id="track-advisory";panel.className="track-advisory hidden";panel.innerHTML=`${trackOutlineMarkup("driver-track-map")}<div><span>LOCAL TRACK SIGNAL</span><strong id="track-advisory-copy"></strong></div>`;display.append(panel)}const signals=activeTrackSignals(state?.trackSignals),suppressed=new Set(["red","checkered","under-review","disqualification","infraction-warning"]).has(state?.activeFlag);panel.classList.toggle("hidden",!signals.length||suppressed);panel.classList.toggle("has-grip",hasGripSignal(state?.trackSignals));panel.querySelectorAll("[data-track-sector]").forEach(path=>{const signal=signals.find(item=>item.id===path.dataset.trackSector);path.setAttribute("class",signal?.className||"")});$("track-advisory-copy").textContent=signals.map(signal=>`${signal.shortLabel} • ${signal.label}`).join(" · ")}
function renderInstructionControls(mode){const current=state?.event?.currentInstruction,active=current&&acknowledgedInstructionTypes.has(current.type),ack=active&&driverUser?state.event?.instructionAcks?.[driverUser.uid]:null,acknowledged=Boolean(ack&&ack.instructionId===current.id),movement=state?.activeFlag==="return-to-start"||mode==="next-session-staging";$("movement-symbol").classList.toggle("hidden",!movement);const button=$("instruction-ack");button.classList.toggle("hidden",!active||!driverProfile);button.classList.toggle("acknowledged",acknowledged);button.disabled=acknowledged;button.textContent=acknowledged?"Acknowledged to Race Control":"Acknowledge Instruction"}
function render(){const mode=getRenderMode(state),enforcement=new Set(["violation-review","white-termination"]).has(mode);timer.classList.toggle("dot-timer",mode==="next-session-countdown");$("steward-brand").classList.toggle("hidden",!enforcement);$("qualifying-leaderboard").classList.toggle("hidden",mode!=="qualifying-live");renderSafetyManagement();renderTrackAdvisory();renderInstructionControls(mode);if(mode==="no-event"){showStatus("NO ACTIVE EVENT","The MRA Steward has not opened an event.");return}if(mode==="test-mode"){showTestMode();return}if(mode==="standby"){showStandbyFlag();return}if(mode==="sprint-live"){showSprint();return}if(mode==="qualifying-live"){showQualifying();return}if(mode==="course-lap"){
 showStatus("SAFETY CAR","COURSE FAMILIARIZATION LAP • FOLLOW SAFETY CAR • NO OVERTAKING",state.event.name);
 applyDisplayClass("display flag-safety-car flash","course-lap");
 return
}
if(mode==="session-live"||mode==="awaiting-finding-start"){showLive();return}
if(mode==="next-session-staging"||mode==="next-session-countdown"){
 const sig=signals["proceed-to-start"],restart=Boolean(state.session?.restart);statusView.classList.add("hidden");liveView.classList.remove("hidden");applyDisplayClass(`display ${mode==="next-session-countdown"?"flag-start-lights":sig.className}`,mode);label.textContent=restart?"RESTART":sig.label;instruction.textContent=mode==="next-session-countdown"?"TEAM SET • GREEN WHEN ALL RED LIGHTS GO OUT":restart?"RETURN TO STARTING LINE • PREPARE TO RESTART":sig.instruction;sessionLine.textContent=`SESSION ${state.session?.number||""} • ${restart?"RESTART":"NEXT HIDING TEAM"}`;if(mode==="next-session-countdown")renderStartDots();else timer.textContent="WAIT";theme.content=mode==="next-session-countdown"?"#171a1f":sig.theme;return
}
if(mode==="safety-car-termination"){
 statusView.classList.add("hidden");liveView.classList.remove("hidden");
 applyDisplayClass("display flag-safety-car flash","safety-car-termination");
 label.textContent="SAFETY CAR";
 instruction.textContent="SESSION TERMINATED • FOLLOW SAFETY CAR • NO OVERTAKING";
 sessionLine.textContent=`SESSION ${state.session?.number||""} • TERMINATED`;
 timer.textContent="ENDED";theme.content="#050505";return
}
if(mode==="violation-review"||mode==="white-termination"){
 statusView.classList.add("hidden");liveView.classList.remove("hidden");
 applyDisplayClass(`display flag-white ${mode==="white-termination"?"flag-disqualified":"flag-under-review"}`,mode);
 label.textContent=mode==="violation-review"?"MRA STEWARD":"DISQUALIFIED";
 instruction.textContent=mode==="violation-review"?"INCIDENT UNDER INVESTIGATION":state.session?.provisionalReason||"RETURN TO STARTING ZONE";
 sessionLine.textContent=`SESSION ${state.session?.number||""}`;
 timer.textContent="ENDED";theme.content="#ffffff";return
}
if(mode==="provisional"||mode==="session-complete"){
 const sig=signals[state.activeFlag]||signals.checkered,s=state.session;
 statusView.classList.add("hidden");liveView.classList.remove("hidden");
 applyDisplayClass(`display ${sig.className}${sig.flash?" flash":""}`,`${mode}:${state.activeFlag}`);
 label.textContent=sig.label;
 instruction.textContent=new Set(["return-to-start","infraction-warning"]).has(state.activeFlag)?sig.instruction:mode==="session-complete"?"OFFICIAL SESSION RESULT":(s?.provisionalReason||sig.instruction);
 sessionLine.textContent=`SESSION ${s?.number||""} • PURSUIT: ${s?.teamNames?.[s.pursuitTeam]||"—"} • EVADING: ${s?.teamNames?.[s.evadingTeam]||"—"}`;
 timer.textContent="ENDED";theme.content=sig.theme;return
}}
function tick(){if(state?.systemState==="next-session-countdown"){renderStartDots();return}if(state?.systemState==="sprint-live"){timer.textContent=state.sprint?.timerMode==="none"?"NO TIMER":fmt(sprintTime());return}if(state?.systemState==="qualifying-live"){timer.textContent=fmtQualifying(qualifyingTime(state.event?.qualifying||{}));return}if(!state?.session||state.systemState!=="session-live")return;if(!state.session.running){timer.textContent=fmt(state.session.remainingMs);return}const factor=state.session.flag==="yellow"?0.5:1;timer.textContent=fmt(Math.max(0,state.session.remainingMs-(Date.now()-(state.session.lastTickAt||Date.now()))*factor))}
function loadVehicleReports(){
 renderPassengerHistory();
 const report=state?.event?.vehicleReports?.[selectedVehicle]||{};
 const reportKey=`${selectedVehicle}:${report.submittedAt||""}`;
 if(!crewEditing&&reportKey!==lastReportKey&&driverProfile){const passengerId=report.passengerId||driverProfile.passengerId||"",passenger=competition.drivers?.[passengerId];driverProfile={...driverProfile,passengerId,passengerName:passenger?.name||report.passengerName||""};renderCrewChoices();lastReportKey=reportKey}
 const profileNames=driverProfile?[driverProfile.teamName||"Independent",driverProfile.passengerName&&`Passenger: ${driverProfile.passengerName}`].filter(Boolean).join(" • "):"Driver profile";$("portal-driver-name").textContent=driverProfile?.driverName||"Signed In";$("portal-mra-number").textContent=driverProfile?.mraNumber||"Legacy profile";$("crew-names").textContent=profileNames;$("crew-action").textContent="Manage";
 const role=state?.session?.pursuitVehicleIds?.includes(selectedVehicle)?"Pursuit":state?.session?.evadingVehicleIds?.includes(selectedVehicle)?"Evading":"Standby";
 $("driver-role").textContent=role;
 const hazards=Object.values(state?.event?.hazards||{}).filter(h=>h.vehicleId===selectedVehicle).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));
 const hazard=hazards.find(item=>item.status!=="resolved")||hazards[0];clearTimeout(resolvedTimer);
 if(!hazard){$("driver-hazard-status").innerHTML="";return}
 const text=hazard.status==="open"?"Sent to Race Control • Awaiting acknowledgment":hazard.status==="acknowledged"?"Acknowledged by Race Control":"Resolved";
 $("driver-hazard-status").innerHTML=`<div class="hazard-status-pill ${escapeHtml(hazard.status)}"><strong>Hazard Report</strong><span>${text}</span></div>`;
 if(hazard.status==="resolved")resolvedTimer=setTimeout(()=>{$("driver-hazard-status").innerHTML=""},4000);
}
function showDriverPortal(show){$("driver-signin").classList.toggle("hidden",!show);tools.classList.toggle("hidden",show);if(show)setTimeout(()=>$("signin-team").focus(),0)}
function renderVehicleOptions(){const ids=Object.keys(LEGACY_VEHICLES),prior=selectedVehicle;if(!ids.includes(selectedVehicle))selectedVehicle="ranger";vehicleSelect.innerHTML=ids.map(id=>`<option value="${escapeHtml(id)}">${escapeHtml(LEGACY_VEHICLES[id].name)}${LEGACY_VEHICLES[id].emergencyOnly?" — Emergency only":""}</option>`).join("");vehicleSelect.value=ids.includes(prior)?prior:selectedVehicle}
function teamDrivers(teamId){return Object.entries(competition.drivers||{}).filter(([id,driver])=>driver.teamId===teamId&&isScoringDriverEligible(id,driver)).sort((a,b)=>a[1].name.localeCompare(b[1].name))}
function renderTeamChoices(){const teams=Object.entries(competition.teams||{}).filter(([,team])=>team.status==="approved").sort((a,b)=>a[1].name.localeCompare(b[1].name)),options=teams.map(([id,team])=>`<option value="${escapeHtml(id)}">${escapeHtml(team.name)}</option>`).join(""),prior=$("signin-team").value,registrationPrior=$("registration-team").value;$("signin-team").innerHTML=options;$("registration-team").innerHTML=options;if(teams.some(([id])=>id===prior))$("signin-team").value=prior;if(teams.some(([id])=>id===registrationPrior))$("registration-team").value=registrationPrior}
function renderCrewChoices(){if(!driverProfile)return;const drivers=teamDrivers(driverProfile.teamId),priorDriver=driverProfile.driverId;if(!drivers.some(([id])=>id===priorDriver)&&drivers.length)applySelectedDriver(drivers[0][0],false);$("team-driver").innerHTML=drivers.map(([id,driver])=>`<option value="${escapeHtml(id)}">${escapeHtml(driver.name)} • MRA ${escapeHtml(driver.mraNumber)}</option>`).join("");$("team-driver").value=driverProfile.driverId;const allDrivers=Object.entries(competition.drivers||{}).filter(([,driver])=>driver.status==="approved").sort((a,b)=>a[1].name.localeCompare(b[1].name));$("passenger-driver").innerHTML='<option value="">No registered passenger</option>'+allDrivers.filter(([id])=>id!==driverProfile.driverId).map(([id,driver])=>`<option value="${escapeHtml(id)}">${escapeHtml(driver.name)} • ${escapeHtml(driver.teamName)} • MRA ${escapeHtml(driver.mraNumber)}</option>`).join("");$("passenger-driver").value=driverProfile.passengerId||""}
function renderPassengerHistory(){const history=Object.values(state?.event?.passengerParticipants||{}),box=$("event-passenger-history");box.classList.toggle("hidden",!history.length);box.innerHTML=history.length?`<span>Passengers recorded this event</span><div>${history.map(item=>`<b>${escapeHtml(item.driverName||competition.drivers?.[item.driverId]?.name||"Registered passenger")}</b>`).join("")}</div><small>Passenger changes are saved. Each person can earn at most one participation point in a points event.</small>`:""}
function applySelectedDriver(driverId,persist=true){const driver=competition.drivers?.[driverId];if(!driver||driver.teamId!==driverProfile?.teamId)return;driverProfile={...driverProfile,driverId,driverName:driver.name,mraNumber:driver.mraNumber,teamName:driver.teamName||competition.teams?.[driver.teamId]?.name||"Team",passengerId:driverProfile.passengerId===driverId?"":driverProfile.passengerId,passengerName:driverProfile.passengerId===driverId?"":driverProfile.passengerName};if(persist)storeDriverProfile(driverProfile)}
function storeDriverProfile(profile){driverProfile=profile;selectedVehicle=profile.vehicleId||selectedVehicle;renderVehicleOptions();vehicleSelect.value=selectedVehicle;localStorage.setItem(PROFILE_KEY,JSON.stringify({...profile,vehicleId:selectedVehicle}));localStorage.setItem("mfma-driver-vehicle",selectedVehicle);renderCrewChoices();syncDriverGatorReason()}
async function submitDriverProfile(){if(!state?.event||!driverProfile)return;await ensureDriverAuth();const emergencyReason=driverProfile.vehicleId==="gator"?normalizeName(driverProfile.gatorReason):null;if(driverProfile.vehicleId==="gator"&&!emergencyReason)throw new Error("A Gator emergency reason is required.");const report={...cleanOccupantReport(driverProfile.driverName,driverProfile.passengerName,serverTimestamp()),driverId:driverProfile.driverId,mraNumber:driverProfile.mraNumber,teamId:driverProfile.teamId,teamName:driverProfile.teamName,passengerId:driverProfile.passengerId||null,passengerMraNumber:driverProfile.passengerId?competition.drivers?.[driverProfile.passengerId]?.mraNumber||null:null,emergencyReason},updates={[`vehicleReports/${driverProfile.vehicleId}`]:report,[`driverParticipants/${driverProfile.driverId}`]:{driverId:driverProfile.driverId,driverName:driverProfile.driverName,mraNumber:driverProfile.mraNumber,teamId:driverProfile.teamId,teamName:driverProfile.teamName,vehicleId:driverProfile.vehicleId,emergencyReason,lastParticipatedAt:serverTimestamp()}};if(driverProfile.passengerId){const passenger=competition.drivers?.[driverProfile.passengerId];updates[`passengerParticipants/${driverProfile.passengerId}`]={driverId:driverProfile.passengerId,driverName:passenger.name,mraNumber:passenger.mraNumber,recordedByTeamId:driverProfile.teamId,participatedAt:serverTimestamp()}}await update(ref(db,"mfma/state/event"),updates)}
function syncStoredDriverProfile(){const remote=state?.event?.vehicleReports?.[driverProfile?.vehicleId];if(!driverProfile||!state?.event||(remote?.driverName===driverProfile.driverName&&remote?.passengerName===(driverProfile.passengerName||"")))return;submitDriverProfile().catch(error=>console.error("Unable to sync Driver Portal profile",error))}
function syncDriverGatorReason(){const gator=vehicleSelect.value==="gator";$("driver-gator-reason-field").classList.toggle("hidden",!gator);if(gator)$("driver-gator-reason").value=driverProfile?.gatorReason||""}
vehicleSelect.onchange=async()=>{selectedVehicle=vehicleSelect.value;localStorage.setItem("mfma-driver-vehicle",selectedVehicle);syncDriverGatorReason();if(selectedVehicle==="gator"){setCrewEditing(true);$("occupant-status").textContent="Record the emergency reason, then save the crew.";return}if(driverProfile){storeDriverProfile({...driverProfile,vehicleId:selectedVehicle,gatorReason:""});try{await submitDriverProfile()}catch(error){$("occupant-status").textContent=friendlyWriteError(error)}}loadVehicleReports()};
function setCrewEditing(open){crewEditing=open;$("occupant-form").classList.toggle("hidden",!open);$("crew-toggle").setAttribute("aria-expanded",String(open));if(open)$("team-driver").focus()}
function ensureDriverAuth(){
 if(driverUser)return Promise.resolve(driverUser);
 if(!driverAuthPromise)driverAuthPromise=signInAnonymously(auth).then(credential=>{driverUser=credential.user;return driverUser}).catch(error=>{driverAuthPromise=null;throw error});
 return driverAuthPromise;
}
function friendlyWriteError(error){console.error("Firebase Driver report write failed",error);return error?.code==="auth/unauthorized-domain"?"Driver reports are not authorized from this site.":error?.code?.includes("permission-denied")||error?.code?.includes("permission_denied")?"Could not send report to Race Control. Connection or permission error.":"Could not send report to Race Control. Check your connection and try again."}
$("crew-toggle").onclick=()=>setCrewEditing(true);$("crew-cancel").onclick=()=>setCrewEditing(false);
$("team-driver").onchange=()=>{const driver=competition.drivers?.[$("team-driver").value];if(!driver)return;$("portal-driver-name").textContent=driver.name;$("portal-mra-number").textContent=driver.mraNumber};
$("occupant-form").onsubmit=async event=>{event.preventDefault();const button=$("crew-submit"),gatorReason=normalizeName($("driver-gator-reason").value);$("occupant-status").textContent="";if(selectedVehicle==="gator"&&!gatorReason){$("occupant-status").textContent="Explain why the emergency vehicle is required.";return}button.disabled=true;button.textContent="Saving…";try{applySelectedDriver($("team-driver").value,false);const passengerId=$("passenger-driver").value,passenger=competition.drivers?.[passengerId];storeDriverProfile({...driverProfile,vehicleId:selectedVehicle,gatorReason:selectedVehicle==="gator"?gatorReason:"",passengerId:passengerId||"",passengerName:passenger?.name||""});if(state?.event)await submitDriverProfile();setCrewEditing(false);loadVehicleReports();$("occupant-status").textContent=state?.event?"Crew updated with Race Control":"Crew selection saved";setTimeout(()=>{$("occupant-status").textContent=""},2500)}catch(error){$("occupant-status").textContent=friendlyWriteError(error)}finally{button.disabled=false;button.textContent="Save Crew"}};
async function requestDriverAccess(){const teamId=$("signin-team").value,team=competition.teams?.[teamId];if(!team||team.status!=="approved")throw new Error("Choose an approved team.");const user=await ensureDriverAuth(),binding=(await get(ref(db,`mfma/driverAccess/${user.uid}`))).val(),boundTeamId=binding?.teamId||competition.drivers?.[binding?.driverId]?.teamId;localStorage.removeItem("mfma-driver-signed-out");if(binding?.status==="approved"&&boundTeamId===teamId){currentBinding=binding;activateApprovedBinding();return}await update(ref(db,`mfma/requests/access/${user.uid}`),{uid:user.uid,teamId,teamName:team.name,status:"pending",requestedAt:serverTimestamp()});throw new Error("Team device access requested. MRA approval is required once for this device.")}
$("driver-signin-form").onsubmit=async event=>{event.preventDefault();const button=$("driver-signin-submit"),statusLine=$("driver-signin-status");statusLine.textContent="";button.disabled=true;button.textContent="Checking…";try{await requestDriverAccess()}catch(error){statusLine.textContent=error.message||friendlyWriteError(error)}finally{button.disabled=false;button.textContent="Continue"}};
$("show-registration").onclick=()=>{$("driver-signin-form").classList.add("hidden");$("driver-registration-form").classList.remove("hidden");$("registration-name").focus()};$("show-signin").onclick=()=>{$("driver-registration-form").classList.add("hidden");$("driver-signin-form").classList.remove("hidden");$("signin-team").focus()};
$("driver-registration-form").onsubmit=async event=>{event.preventDefault();const statusLine=$("registration-status");try{const user=await ensureDriverAuth(),name=normalizeName($("registration-name").value),teamId=$("registration-team").value,teamName=competition.teams?.[teamId]?.name,requestedMraNumber=normalizeMraNumber($("registration-number").value);if(!teamName)throw new Error("Choose one of the two registered teams.");await update(ref(db,`mfma/requests/registrations/${user.uid}`),{uid:user.uid,name,teamId,teamName,requestedMraNumber,status:"pending",requestedAt:serverTimestamp()});statusLine.textContent="Registration sent to MRA Race Management for approval."}catch(error){statusLine.textContent=error.message||friendlyWriteError(error)}};
$("driver-sign-out").onclick=()=>{driverProfile=null;currentBinding=null;localStorage.removeItem(PROFILE_KEY);localStorage.setItem("mfma-driver-signed-out","1");showDriverPortal(true)};
async function submitHazardRequest(kind,button){
 const safetyCar=kind==="safety-car",label=safetyCar?"Safety Car":"Red Flag";
 if(!state?.event){$("driver-hazard-status").textContent="No active event.";return}
 document.querySelectorAll("[data-hazard-request]").forEach(item=>item.disabled=true);button.textContent="Sending…";
 try{await ensureDriverAuth();const hazardRef=push(ref(db,"mfma/state/event/hazards"));const report=cleanHazardReport({vehicleId:selectedVehicle,description:`${label} requested`,requestStopClock:!safetyCar,requestSafetyCar:safetyCar},serverTimestamp());if(driverProfile?.driverId)Object.assign(report,{driverId:driverProfile.driverId,mraNumber:driverProfile.mraNumber});await update(hazardRef,report)}
 catch(error){$("driver-hazard-status").textContent=friendlyWriteError(error)}
 finally{document.querySelectorAll("[data-hazard-request]").forEach(item=>item.disabled=false);button.textContent=`Request ${label}`}
}
document.querySelectorAll("[data-hazard-request]").forEach(button=>button.onclick=()=>submitHazardRequest(button.dataset.hazardRequest,button));
$("instruction-ack").onclick=async()=>{const current=state?.event?.currentInstruction;if(!current||!driverProfile||!acknowledgedInstructionTypes.has(current.type))return;const button=$("instruction-ack");button.disabled=true;button.textContent="Sending Acknowledgement…";try{const user=await ensureDriverAuth();await update(ref(db,`mfma/state/event/instructionAcks/${user.uid}`),{instructionId:current.id,type:current.type,vehicleId:selectedVehicle,driverId:driverProfile.driverId,teamId:driverProfile.teamId,acknowledgedAt:serverTimestamp()})}catch(error){button.disabled=false;button.textContent="Try Acknowledgement Again";$("driver-hazard-status").textContent=friendlyWriteError(error)}};
function closePortalSheet(){$("portal-sheet").classList.add("hidden")}
function openStats(){
 const seasonId=currentSeasonId(),row=competition?.standings?.[seasonId]?.drivers?.[driverProfile?.driverId]||{},allArchives=Object.values(competition?.archives||{}).flatMap(season=>Object.entries(season||{})),allAdjustments=Object.assign({},...Object.values(competition.pointsAdjustments||{})),career=applyStandingsAdjustments(rebuildStandings(Object.fromEntries(allArchives)),allAdjustments).drivers?.[driverProfile?.driverId]||{},archives=allArchives.map(([,event])=>event).filter(event=>event.classification?.some(entry=>entry.driverId===driverProfile?.driverId)||event.passengerParticipation?.some(entry=>entry.driverId===driverProfile?.driverId)).sort((a,b)=>(b.endedAt||0)-(a.endedAt||0));
 $("portal-sheet-title").textContent=driverProfile.driverName;$("portal-sheet-content").innerHTML=`<h3>${seasonId} Season${row.provisional?" • Provisional":""}</h3><div class="portal-stat-grid"><article><strong>${row.points||0}</strong><span>Total Points</span></article><article><strong>${row.sessionPoints||0}</strong><span>Session Points</span></article><article><strong>${row.eventPoints||0}</strong><span>At-large Points</span></article><article><strong>${row.participationPoints||0}</strong><span>Participation</span></article></div>${row.droppedPoints?`<p class="status-note">${row.droppedPoints} lowest at-large point${row.droppedPoints===1?"":"s"} dropped.</p>`:""}<h3>Career</h3><div class="portal-stat-grid"><article><strong>${career.points||0}</strong><span>Total Points</span></article><article><strong>${career.sessionPoints||0}</strong><span>Session Points</span></article><article><strong>${career.eventPoints||0}</strong><span>At-large Points</span></article><article><strong>${career.participationPoints||0}</strong><span>Participation</span></article></div><h3>Prior Races</h3><div class="portal-history">${archives.map(event=>{const result=event.classification?.find(entry=>entry.driverId===driverProfile.driverId),sessions=(event.sessionResults||[]).flatMap(item=>item.entrants||[]).filter(entry=>entry.driverId===driverProfile.driverId).reduce((sum,entry)=>sum+(entry.points||0),0),passenger=event.passengerParticipation?.some(entry=>entry.driverId===driverProfile.driverId),noPoints=event.status==="void"||event.pointsEvent===false;return `<article><span><strong>${escapeHtml(event.name)}</strong><small>${escapeHtml(event.date||"")} • ${escapeHtml(event.seasonId||"")} • ${event.status==="void"?"VOID":event.pointsEvent===false?"Non-points":"Points event"}</small></span><b>${noPoints?"No points":`${sessions} session${result?` + ${result.points} at-large`:passenger?" + 1 participation":""}`}</b></article>`}).join("")||"<p>No archived races yet.</p>"}</div>`;$("portal-sheet").classList.remove("hidden")
}
$("view-driver-stats").onclick=openStats;$("close-portal-sheet").onclick=closePortalSheet;$("portal-sheet").onclick=event=>{if(event.target===$("portal-sheet"))closePortalSheet()};
function renderSoundStatus({state:audioState}){soundButton.textContent=audioState==="enabled"?"Sound On":"Enable Sound";soundButton.dataset.state=audioState}
soundButton.onclick=async()=>{try{await enableSounds()}catch(error){console.warn("Unable to enable display sounds",error)}renderSoundStatus(getSoundStatus())};
onSoundStatus(renderSoundStatus);
onValue(stateRef,s=>{const previous=state;state=s.val()||{systemState:"no-event"};playStateTransition(previous,state);status.className="display-status live";statusText.textContent="LIVE";render();loadVehicleReports();syncStoredDriverProfile()},e=>{status.className="display-status error";statusText.textContent="ERROR";showStatus("CONNECTION ERROR","Unable to reach Race Control.")});
function activateApprovedBinding(){const teamId=currentBinding?.teamId||competition.drivers?.[currentBinding?.driverId]?.teamId;if(currentBinding?.status!=="approved"||!teamId||localStorage.getItem("mfma-driver-signed-out"))return;const drivers=teamDrivers(teamId),stored=driverProfile?.teamId===teamId&&competition.drivers?.[driverProfile.driverId]?driverProfile:null,[driverId,driver]=drivers.find(([id])=>id===stored?.driverId)||drivers[0]||[];if(!driver)return;storeDriverProfile({...stored,driverId,driverName:driver.name,mraNumber:driver.mraNumber,teamId,teamName:driver.teamName||competition.teams?.[teamId]?.name||"Team",vehicleId:stored?.vehicleId||selectedVehicle,passengerId:stored?.passengerId||"",passengerName:stored?.passengerName||""});showDriverPortal(false);loadVehicleReports()}
onValue(ref(db,"mfma/competition"),snapshot=>{competition=snapshot.val()||{};competition.standings=Object.fromEntries(Object.entries(competition.archives||{}).map(([seasonId,archives])=>[seasonId,applyStandingsAdjustments(rebuildStandings(archives),competition.pointsAdjustments?.[seasonId])]));renderVehicleOptions();renderTeamChoices();if(driverProfile?.driverId){const driver=competition.drivers?.[driverProfile.driverId];if(driver)storeDriverProfile({...driverProfile,driverName:driver.name,mraNumber:driver.mraNumber,teamId:driver.teamId,teamName:driver.teamName||competition.teams?.[driver.teamId]?.name||"Team"})}activateApprovedBinding();loadVehicleReports()});
onAuthStateChanged(auth,user=>{driverUser=user;currentBinding=null;if(accessUnsubscribe){accessUnsubscribe();accessUnsubscribe=null}if(!user){ensureDriverAuth().catch(error=>console.error("Anonymous Driver authentication failed",error));return}accessUnsubscribe=onValue(ref(db,`mfma/driverAccess/${user.uid}`),snapshot=>{currentBinding=snapshot.val();if(currentBinding?.status==="approved")activateApprovedBinding();else{driverProfile=null;localStorage.removeItem(PROFILE_KEY);showDriverPortal(true)}})});
renderVehicleOptions();renderTeamChoices();showDriverPortal(!driverProfile);awake();setInterval(tick,250);
