const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm");
const source=fs.readFileSync("competition-model.js","utf8").replaceAll("export ","");const context={};vm.createContext(context);vm.runInContext(`${source};this.api={DEFAULT_POINTS,approvedVehicles,findDriver,buildEventArchive,rebuildStandings,applyStandingsAdjustments,normalizeMraNumber,teamBranding,registeredVehicleId,driverCompetitionRole,isScoringDriverEligible,sortedStandings}`,context);const m=context.api;

test("driver sign-in matches normalized name and MRA number",()=>{const match=m.findDriver({d1:{name:"Alex Driver",mraNumber:"MRA 104",status:"approved"}}," alex   driver ","mra104");assert.equal(match[0],"d1")});
test("only approved submitted vehicles join the three legacy vehicles",()=>{const result=m.approvedVehicles({newcar:{name:"New Car",status:"approved"},waiting:{name:"Waiting",status:"pending"}});assert.deepEqual(Object.keys(result).sort(),["gator","newcar","ranger","shelly"])});
test("team points follow the driver's affiliation and not a passenger",()=>{const competition={drivers:{d1:{name:"Driver One",mraNumber:"101",teamId:"team-red",teamName:"Red Team"}},seasons:{"2026":{points:[10,6]}}};const state={event:{name:"Round 1",scores:{a:3,b:1},vehicleReports:{car1:{driverId:"d1",driverName:"Driver One",teamId:"wrong-passenger-team"}}},session:{setup:{vehicleIds:["car1","car2"]}}};const archive=m.buildEventArchive(state,competition,{seasonId:"2026",date:"2026-09-12",endedAt:1});assert.equal(archive.classification[0].teamId,"team-red");const standings=m.rebuildStandings({round1:archive});assert.equal(standings.teams["team-red"].points,10);assert.equal(standings.teams["wrong-passenger-team"],undefined)});
test("known teams resolve to their championship branding",()=>{assert.match(m.teamBranding("monarch-mfma-team").emblem,/monarch-team-emblem/);assert.equal(m.teamBranding("future-team").emblem,null)});
test("registered passengers earn one driver-only participation point after a completed session",()=>{const competition={drivers:{d1:{name:"Driver",mraNumber:"1",teamId:"team-a",teamName:"Team A",status:"approved"},p1:{name:"Passenger",mraNumber:"2",teamId:"team-b",teamName:"Team B",status:"approved"}},seasons:{"2026":{points:[5]}}},state={event:{name:"Round",scores:{a:1},vehicleReports:{ranger:{driverId:"d1",driverName:"Driver",teamId:"team-a"}},passengerParticipants:{p1:{driverId:"p1"}},participationSessions:{p1:1}},session:{setup:{vehicleIds:["ranger"]}}},archive=m.buildEventArchive(state,competition,{seasonId:"2026"}),standings=m.rebuildStandings({round:archive});assert.equal(archive.passengerParticipation.length,1);assert.equal(standings.drivers.p1.points,1);assert.equal(standings.drivers.p1.participationPoints,1);assert.equal(standings.teams["team-b"],undefined);assert.equal(standings.vehicles.p1,undefined)});
test("multiple passenger switches award each verified passenger only once",()=>{const competition={drivers:{p1:{name:"Passenger One",status:"approved"},p2:{name:"Passenger Two",status:"approved"},p3:{name:"Seat Touch",status:"approved"}}},state={event:{pointsEvent:true,passengerParticipants:{p1:{driverId:"p1"},p2:{driverId:"p2"},p3:{driverId:"p3"}},participationSessions:{p1:2,p2:1}}},archive=m.buildEventArchive(state,competition,{seasonId:"2026"}),standings=m.rebuildStandings({round:archive});assert.equal(archive.passengerParticipation.map(row=>row.driverId).sort().join(","),"p1,p2");assert.equal(standings.drivers.p1.points,1);assert.equal(standings.drivers.p2.points,1);assert.equal(standings.drivers.p3,undefined)});

test("fair defaults and honorary roles protect the scoring driver selection",()=>{assert.equal(m.DEFAULT_POINTS.join(","),"5,3");assert.equal(m.driverCompetitionRole("mra-16",{status:"approved"}),"primary");assert.equal(m.driverCompetitionRole("mra-3",{status:"approved"}),"honorary");assert.equal(m.isScoringDriverEligible("mra-3",{status:"approved"}),false)});

test("sporting ties share a rank instead of being broken alphabetically",()=>{const rows=m.sortedStandings({a:{name:"Zulu",points:5,wins:1},b:{name:"Alpha",points:5,wins:1}});assert.equal(rows[0].championshipRank,1);assert.equal(rows[1].championshipRank,1);assert.equal(rows[0].tied,true);assert.equal(rows[1].tied,true)});
test("non-points events remain archived but never enter standings",()=>{const standings=m.rebuildStandings({exhibition:{pointsEvent:false,classification:[{driverId:"d1",driverName:"Driver",teamId:"team-a",teamName:"Team A",vehicleId:"ranger",points:10,position:1}],passengerParticipation:[{driverId:"p1",driverName:"Passenger",points:1}]}});assert.deepEqual(Object.keys(standings.drivers),[]);assert.deepEqual(Object.keys(standings.teams),[]);assert.deepEqual(Object.keys(standings.vehicles),[])});
test("void results stay archived but are removed from standings",()=>{const standings=m.rebuildStandings({round:{status:"void",classification:[{driverId:"d1",teamId:"team-a",vehicleId:"ranger",points:10,position:1}]}});assert.equal(Object.keys(standings.drivers).length,0)});
test("audited adjustments add or deduct points without rewriting results",()=>{const standings=m.applyStandingsAdjustments(m.rebuildStandings({round:{classification:[{driverId:"d1",driverName:"Driver",points:10,position:1}]}}),{penalty:{type:"drivers",entityId:"d1",entityName:"Driver",points:-2,status:"active"},voided:{type:"drivers",entityId:"d1",points:99,status:"void"}});assert.equal(standings.drivers.d1.points,8)});
test("team names resolve the two official scoring sides",()=>{const competition={teams:{"team-one":{name:"Team One"},"team-two":{name:"Team Two"}},drivers:{d1:{name:"Driver One",teamId:"team-one",status:"approved"}},seasons:{"2026":{points:[10,6]}}},state={event:{scores:{a:2,b:1},teamNames:{a:"Team One",b:"Team Two"},vehicleReports:{ranger:{driverId:"d1",driverName:"Driver One",teamId:"team-one"}}},session:{setup:{vehicleIds:["ranger","gator"]}}},archive=m.buildEventArchive(state,competition,{seasonId:"2026"});assert.equal(archive.classification.length,2);assert.equal(archive.classification[0].teamId,"team-one");assert.equal(archive.classification[1].teamId,"team-two");assert.equal(archive.classification.map(row=>row.points).join(","),"10,6")});
